version: 2

formats:
  - htmlzip
  - pdf

python:
   version: 3.6
   install:
      - method: pip
        path: .
        extra_requirements:
            - lint
   system_packages: true

sphinx:
  configuration: docs/conf.py